### Numpy ndarray
**ndarray: N차원(Dimesion) 배열(Array) 객체 **

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
print('list1: ', list1)
print('list1 type: ', type(list1))

array1 = np.array(list1)
print('array1: ', array1)
print('array1 type: ', type(array1))

list1:  [1, 2, 3]
list1 type:  <class 'list'>
array1:  [1 2 3]
array1 type:  <class 'numpy.ndarray'>


- ndarray의 형태(shape)와 차원

In [3]:
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


- ndarray 데이터 값 타입

In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)   # convert to str

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- astype()을 통한 타입 변환

In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- ndarray에서 axis 기반의 연산함수 수행

In [8]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


- ndarray를 편리하게 생성하기 - arange, zeros, ones

In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [10]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- ndarray의 shape를 변경하는 reshape()

In [11]:
array1 = np.arange(10)
print('array1: ', array1)

array2 = array1.reshape(2,5)
print('array2: ', array2)

array3 = array1.reshape(5,2)
print('array3: ', array3)

array1:  [0 1 2 3 4 5 6 7 8 9]
array2:  [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
# 변환할 수 없는 shape 구조를 입력하면 오류 발생
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

- reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray 형태 변환

In [13]:
array1 = np.arange(10)
print(array1)

# col axis 크기는 5에 고정하고 raw axis 크기를 이에 맞춰 자동으로 변환 즉, 2X5 형태로 변환
array2 = array1.reshape(-1,5)
print('array2 shape: ', array2.shape)
print('array2: \n', array2)

# raw axis 크기는 5로 고정하고 col axis 크기는 이에 맞춰 자동으로 변환 즉, 5X2 형태로 변환
array3 = array1.reshape(5,-1)
print('array3 shape: ', array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape:  (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# reshape()는 (-1, 1), (-1,)와 같은 형태로 주로 사용됨
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, col axis 크기는 반드시 1이어야 함
array2d_1 = array1.reshape(-1,1)
print('array2d_1 shape: ', array2d_1.shape)
print('array2d_1:\n', array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1, )
print('array1d shape: ', array1d.shape)
print('array1d:\n', array1d)

array2d_1 shape:  (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape:  (5,)
array1d:
 [0 1 2 3 4]


In [15]:
# -1을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
# 반드시 -1 값은 1개의 인자만 입력해야함
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

### ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)